print()
print(" "*4,end="*\n")
print(" " * 3, " ", sep="*", end="*\n")
print(" " * 2, " " * 3,sep="*", end="*\n")
print(" ", " " * 5, sep="*", end="*\n")
print("*" * 3, "*" * 3, sep=" " * 3, end="\n")
print(" " * 2, " " * 3, sep="*", end="*\n")
print(" " * 2, " " * 3, sep="*", end="*\n")
print(" " * 2, "*" * 3, sep="*", end="*\n")
